using AutoMapper;
using Domain.Models.PatientModule;
using Shared.Dtos.PatientModule.PatientDtos;

namespace Services.MappingProfiles.PatientModule
{
    public class PatientProfile : Profile
    {
        public PatientProfile()
        {
            // Address Mapping
            CreateMap<Address, AddressDto>().ReverseMap();

            // Patient Mapping -> PatientResultDto
            CreateMap<Patient, PatientResultDto>()
                .ForMember(dest => dest.Gender, options => options.MapFrom(src => src.Gender.ToString()))
                .ForMember(dest => dest.BloodType, options => options.MapFrom(src => src.BloodType.HasValue ? src.BloodType.ToString() : null))
                .ForMember(dest => dest.Status, options => options.MapFrom(src => src.Status.ToString()));

            // CreatePatientDto -> Patient Mapping
            CreateMap<CreatePatientDto, Patient>()
    // IGNORE: Id (auto-generated by database)
    .ForMember(dest => dest.Id, options => options.Ignore())

    // IGNORE: MedicalRecordNumber (generated in service using GenerateMedicalRecordNumberAsync)
    .ForMember(dest => dest.MedicalRecordNumber, options => options.Ignore())

    // IGNORE: Status (set to Active by default in service)
    .ForMember(dest => dest.Status, options => options.Ignore())

    // IGNORE: RegistrationDate (set to current date in service)
    .ForMember(dest => dest.RegistrationDate, options => options.Ignore())

    // IGNORE: Navigation Properties (relationships with other tables)
    // These are NOT part of patient creation, they're managed separately
    .ForMember(dest => dest.PatientAllergies, options => options.Ignore())
    .ForMember(dest => dest.PatientMedicalHistories, options => options.Ignore())
    .ForMember(dest => dest.EmergencyContacts, options => options.Ignore());

            // UpdatePatientDto -> Patient Mapping
            // update is handled in the service 
        }
    }
}
